[computer]
host = "laptop"    # required
users = ["andrew"]
disk = "nvme0n1"   # required if using this config to install nixos

[desktop]
environment = "plasma"            # required
modules = ["panels/windows-like"]
