[computer]
host = "laptop"    # required
users = ["andrew"]
disk = "nvme0n1"   # required if using this config to install nixos

[desktop]
environment = "niri" # required
modules = []

[hardware]
keyboard = { layout = "us", variant = "" } # all required
